spring:
  application:
    name: display
  boot:
    admin:
      client:
        url: http://localhost:9002
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"